#!/usr/bin/env python3
import numpy as np

np.savez('mf_scores.npz',
         row=np.asarray([0, 0, 1, 1, 2, 2, 2, 3]),
         col=np.asarray([1, 3, 0, 2, 1, 3, 5, 4]),
         val=np.asarray([10, 15, 1, 2, 10, 30, 20, 5]),
         p2r={'p0':0, 'p1':1, 'p2':2, 'p3':3},
         shape=(4, 6))


np.savez('mf_gterms.npz',
         row=np.asarray([0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5]),
         col=np.asarray([0, 4, 5, 6, 4, 6, 1, 2, 0, 6, 3, 4, 2]),
         val=np.ones(13),
         t2c={'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6},
         shape=(6, 7))
